from typing import Protocol, Sequence


class ProviderError(RuntimeError):
    pass


class ExecutionProvider(Protocol):
    provider_id: str

    def capabilities(self) -> list[str]: ...

    def discover(self) -> dict[str, object]: ...

    def paper_order_contract(self) -> dict[str, object]: ...

    def market_ticker(self, symbol: str) -> dict[str, object]: ...

    def candles(self, symbol: str, interval: str = "1m") -> dict[str, object]: ...

    def instrument(self, symbol: str) -> dict[str, object]: ...

    def account(self) -> dict[str, object]: ...

    def paper_order(self, symbol: str, side: str, notional: object, market_result: dict[str, object] | None = None, instrument_result: dict[str, object] | None = None) -> dict[str, object]: ...

    def paper_order_detail(self, reference_key: str, reference: str) -> dict[str, object]: ...

    def verify_execution(self, value: dict[str, object]) -> bool: ...

    def normalize_result(self, value: dict[str, object], tool: str, arguments: dict[str, object] | None = None) -> dict[str, object]: ...

    def resolve_symbol(self, allowed_symbols: Sequence[str]) -> tuple[str | None, dict[str, object] | None]: ...
